version: '3.8'

services:
  filmhub:
    restart: always
    build: ./
    command: sh -c "sleep 5 && ./filmhub"
    ports:
      - 8000:8000
    depends_on:
      - db
    environment:
      - DB_PASSWORD=password

  db:
    restart: always
    image: postgres:latest
    volumes:
      - ./.database/postgres/data:/var/lib/postgresql/data
      - ./migrations/000001_init_up.sql:/docker-entrypoint-initdb.d/000001_init_up.sql

    environment:
      - POSTGRES_DB=filmdb
      - POSTGRES_USER=postgres  
      - POSTGRES_PASSWORD=password
    ports:
      - 5436:5432 

