version: '3.3'

services:
  db:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_DB=filmdb
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    ports:
      - '5432:5432'
    volumes:
      - ./migrations:/migrations 
    networks:
      - postgres
    healthcheck:
      test: ["CMD", "pg_isready", "-h", "localhost", "-U", "postgres"]
      timeout: 20s
      retries: 10

  app:
    restart: always
    build: .
    ports:
      - '8080:8080'
    depends_on:
      db:
        condition: service_healthy
    environment:
      - DB_USERNAME=postgres
      - DB_PASSWORD=password
      - DB_DB=filmdb
      - DB_HOST=db
      - DB_PORT=5432
    links:
      - db
    networks:
      - postgres
    volumes:
      - .:/src

volumes:
  db:
    driver: local

networks:
  postgres:
    driver: bridge
